# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 200
  wandb_project: NeuProNet

checkpoint:
  save_interval: 1
  save_interval_updates: 0
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: accuracy
  maximize_best_checkpoint_metric: true
  # restore_file: /media/SSD/tungtk2/fairseq/outputs/2022-03-22/13-57-49/checkpoints/checkpoint_last.pt

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: label
  profiling: false
  auto_encoder: false

dataset:
  num_workers: 1
  batch_size: 64
  skip_invalid_size_inputs_valid_test: true
  # validate_after_updates: 50
  # validate_interval: 1000
  valid_subset: valid

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: NeuProNet
  class_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  loss_weights: [0.99, 0.01]

optimization:
  max_update: 6140
  lr: [1e-4]
  sentence_avg: true
  update_freq: [1]
  max_epoch: 50

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08
  weight_decay: 4e-3

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.6, 0.3]
  final_lr_scale: 0.05
  # _name: fixed

model:
  _name: CNN_NPN
  profile_extractor_path: None
  no_pretrained_weights: true
  apply_mask: true
  mask_prob: 0.3
  mask_channel_prob: 0.25
  mask_channel_length: 32
  layerdrop: 0.2
  activation_dropout: 0.2
  feature_grad_mult: 1
  freeze_finetune_updates: 0
  final_dropout: 0.2
  clf_output_dim: 6
  batch_mask: true
